import openapiTS, { astToString } from "openapi-typescript";
import { parse } from "yaml";

export const SPEC_VERSION = "2026.08.4";
export const SPEC_URL = `https://raw.githubusercontent.com/okta/okta-management-openapi-spec/master/dist/${SPEC_VERSION}/management-oneOfInheritance.yaml`;

const rsp = await fetch(SPEC_URL);
if (!rsp.ok) throw new Error(`fetch ${SPEC_URL}: ${rsp.status}`);
const text = await rsp.text();
const spec = parse(text) as { paths: Record<string, unknown>; info: { version: string } };

const ast = await openapiTS(text, {});
await Bun.write("src/okta/schema.d.ts", `// GENERATED by scripts/gen-types.ts from Okta management spec ${spec.info.version}. Do not edit.\n${astToString(ast)}`);
await Bun.write("src/okta/spec-paths.json", JSON.stringify(Object.keys(spec.paths).sort(), null, 1) + "\n");
console.log(`spec ${spec.info.version}: ${Object.keys(spec.paths).length} paths`);
