import openapiTS, { astToString } from "openapi-typescript";
import { parse } from "yaml";

export const SPEC_VERSION = "2026.08.4";
export const SPEC_URL = `https://raw.githubusercontent.com/okta/okta-management-openapi-spec/master/dist/${SPEC_VERSION}/management-oneOfInheritance.yaml`;
export const GOV_SPEC_URL = `https://raw.githubusercontent.com/okta/okta-management-openapi-spec/master/dist/${SPEC_VERSION}/governance-combined-production-reference-oneOfInheritance.yaml`;

async function emit(url: string, dts: string, paths: string): Promise<void> {
  const rsp = await fetch(url);
  if (!rsp.ok) throw new Error(`fetch ${url}: ${rsp.status}`);
  const text = await rsp.text();
  const spec = parse(text) as { paths: Record<string, unknown>; info: { version: string } };

  const ast = await openapiTS(text, {});
  await Bun.write(dts, `// GENERATED by scripts/gen-types.ts from Okta management spec ${spec.info.version}. Do not edit.\n${astToString(ast)}`);
  await Bun.write(paths, JSON.stringify(Object.keys(spec.paths).sort(), null, 1) + "\n");
  console.log(`spec ${spec.info.version}: ${Object.keys(spec.paths).length} paths`);
}

await emit(SPEC_URL, "src/okta/schema.d.ts", "src/okta/spec-paths.json");
await emit(GOV_SPEC_URL, "src/okta/gov-schema.d.ts", "src/okta/gov-spec-paths.json");
